### ISSUE TITLE
Getting Error while applying for mongodb code

### ISSUE THREAD

**Issue by sohailg** [arpan45/mongodb-cluster-kubernetes#1]
Error: Authentication failed. :
connect@src/mongo/shell/mongo.js:372:17
@(connect):2:6
exception: connect failed
exiting with code 1

**Comment by arpan45** [comment]
Try changing the credentials at mongoldb-secrets.yaml. Make sure it is properly encoded. 
For example:
password: cGFzc3dvcmQxMjM= //password123   
username: YWRtaW51c2Vy //adminuser
